[package]
name = "playground"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vulkano = "0.35.1"

[profile.dev]
opt-level = 1
